<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INLM-MohitR-2.local" name="testcases.AssignmentTest" tests="12" failures="2" timestamp="2021-10-16T16:57:35 IST" time="74.297" errors="0">
  <testcase name="codlessVerification" time="3.856" classname="testcases.AssignmentTest"/>
  <system-out/>
  <testcase name="communityVerification" time="6.888" classname="testcases.AssignmentTest"/>
  <system-out/>
  <testcase name="pageLoad" time="2.331" classname="testcases.AssignmentTest"/>
  <system-out/>
  <testcase name="navigateBlog" time="4.706" classname="testcases.AssignmentTest"/>
  <system-out/>
  <testcase name="allIntegration" time="13.372" classname="testcases.AssignmentTest"/>
  <system-out/>
  <testcase name="navigateBlog" time="7.074" classname="testcases.AssignmentTest"/>
  <system-out/>
  <testcase name="communityVerification" time="7.609" classname="testcases.AssignmentTest"/>
  <system-out/>
  <testcase name="pageLoad" time="2.737" classname="testcases.AssignmentTest"/>
  <system-out/>
  <testcase name="learnMore" time="5.494" classname="testcases.AssignmentTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected-&gt; Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest
 Actual-&gt; TestingWhiz Integration | LambdaTest
 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected-> Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest
 Actual-> TestingWhiz Integration | LambdaTest
 expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testcases.AssignmentTest.learnMore(AssignmentTest.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- learnMore -->
  <system-out/>
  <testcase name="codlessVerification" time="3.545" classname="testcases.AssignmentTest"/>
  <system-out/>
  <testcase name="learnMore" time="4.493" classname="testcases.AssignmentTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected-&gt; Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest
 Actual-&gt; TestingWhiz Integration | LambdaTest
 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected-> Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest
 Actual-> TestingWhiz Integration | LambdaTest
 expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testcases.AssignmentTest.learnMore(AssignmentTest.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- learnMore -->
  <system-out/>
  <testcase name="allIntegration" time="12.192" classname="testcases.AssignmentTest"/>
  <system-out/>
</testsuite> <!-- testcases.AssignmentTest -->
